### ISSUE TITLE
LauncherSubsystem null error

### ISSUE THREAD

**Issue by jbko6** [robototes/Crescendo2024#29]
When LauncherSubsystem is enabled and run in simulation a null error results

`Error at frc.team2412.robot.subsystems.LauncherSubsystem.getAngle(LauncherSubsystem.java:119): Unhandled exception: java.lang.NullPointerException: 
Cannot invoke "com.revrobotics.SparkAbsoluteEncoder.getPosition()" because "this.launcherAngleEncoder" is null`

The issue is in line 50 of LauncherSubsystem `.add("Launcher angle", getAngle())`
The encoder is not yet initialized when `getAngle()` is called

**Comment by iamawesomecat** [comment]
fixed :D
