### ISSUE TITLE
Add feedforward property to SparkPIDWidget 

### ISSUE THREAD

**Issue by jamesdooley4** [robototes/Crescendo2024#34]
Should use `setFF` and `getFF` here to enable easy tweaking of the feedforward gain constant:
https://github.com/robototes/Crescendo2024/blame/e5d2fd6a6d25049a37705ddc76b2a92b5178fcd9/src/main/java/frc/team2412/robot/util/SparkPIDWidget.java#L24

**Comment by jbko6** [comment]
this is definitely a good first issue for me
