### ISSUE TITLE
Update laptops, project to WPILib 2024.2.1

### ISSUE THREAD

**Issue by TAKBS2412** [robototes/Crescendo2024#39]
- [x] Update drive station laptops to use 2024 WPILib tools, not just the beta (to avoid the "Would you like to import this project into 2024?" popups) if we haven't done that already
- [x] Update Crescendo2024 to use the [latest version of WPILib](https://github.com/wpilibsuite/allwpilib/releases/latest)

**Comment by jbko6** [comment]
all DS are up to date except DS 2
