### ISSUE TITLE
Selected auto path keeps running after match starts

### ISSUE THREAD

**Issue by jamesdooley4** [robototes/Crescendo2024#86]
@jbko6  - looking at the wpilog logs from E9 match at Glacier Peak, I noticed the "NT\Shuffleboard\Match\Selected auto\Robot" values keep cycling even after the match started. Can you see how to stop those once the robot is enabled, to save some CPU time and memory on the Rio?

**Comment by KangarooKoala** [comment]
Currently the selected auto value is updated via a call to `addPeriodic()`. The quickest way to fix it would probably be to make `AutonomousField.update()` return early if `RobotBase/DriverStation.isEnabled()` (which seems to be pretty cheap, just a mutex lock and some variable reads).

**Comment by jbko6** [comment]
haha I was just looking at the code and came to the same conclusion

**Comment by TAKBS2412** [comment]
Is @jbko6 the correct assignee, or should it be @KangarooKoala who implemented the selected auto preview earlier?

(Realistically, I think either one would do the same thing, but wondering about work distribution).
