### ISSUE TITLE
AutoBuilder.buildAutoChooser() called twice at robotInit()

### ISSUE THREAD

**Issue by jamesdooley4** [robototes/Crescendo2024#96]
https://github.com/robototes/Crescendo2024/blob/5e5ed4b1c32ddec2502690af5c22a474aaf4ad89/src/main/java/frc/team2412/robot/Robot.java#L91

Seems at least like a perf issue, and perhaps a crash if the drivebase subsystem isn't enabled.

**Comment by TAKBS2412** [comment]
Also see #90, which is likely related.
